server:
  port: 8080

management:
  health:
    redis:
      enabled: false
#
#spring:
#redis:
#database: 1
#host: 192.168.1.222
#port: 6379
#jedis:
#pool:
#max-active: 100
#max-idle: 10
#max-wait: 100000
#timeout: 5000